"""add platform user roles

Revision ID: bbf9c32d8218
Revises: 2ac5d771510f
Create Date: 2026-08-24 15:37:02.995101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf9c32d8218'
down_revision = '2ac5d771510f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_role', sa.String(length=20), server_default='member', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('platform_role')

    # ### end Alembic commands ###
